rabbitmq_service:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq_service"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: was
      RABBITMQ_DEFAULT_PASS: was
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq_service"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"